(define (problem vac)

	(:domain vaccine)
	
	(:objects
		truck1 truck2 truck3 truck4 truck5 truck6 truck7 truck8 truck9 truck10 - truck
		truck11 truck12 truck13 truck14 truck15 truck16 truck17 truck18 truck19 truck20 - truck
		
		plane1 plane2 plane3 plane4 plane5 plane6 plane7 plane8 plane9 plane10 - plane
		
		drone1 drone2 drone3 drone4 drone5 drone6 drone7 drone8 drone9 drone10 drone11 drone12 drone13 drone14 drone15 drone16 drone17 drone18 - drone
        drone19 drone20 drone21 drone22 drone23 drone24 drone25 drone26 drone27 drone28 drone29 drone30 drone31 drone32 drone33 drone34 - drone
        drone3 drone36 drone37 drone38 drone39 drone40 drone41 drone42 drone43 drone44 drone45 drone46 drone47 drone48 drone49 drone50 - drone
        drone51 drone52 drone53 drone54 drone55 drone56 drone57 drone58 drone59 drone60 drone61 drone62 drone63 drone64 drone65 drone66 - drone
        drone67 drone68 drone69 drone70 drone71 drone72 drone73 drone74 drone75 drone76 drone77 drone78 drone79 drone80 drone81 drone82 - drone
        drone83 drone84 drone85 drone86 drone87 drone88 drone89 drone90 drone91 drone92 drone93 drone94 drone95 drone96 drone97 drone98 drone99 - drone 
        drone100 drone101 drone102 drone103 drone104 drone105 drone106 drone107 drone108 drone109 drone110 drone111 drone112 drone113 - drone
        drone114 drone115 drone116 drone117 drone118 drone119 drone120 drone121- drone
        CENTRAL_VACC_POINT - location
		LAZIO RM RM1 RM2 RM3 VT VT1 VT2 VT3 LZ1 LZ11 LZ12 LZ13 RI RI1 RI2 RI3 LT LT1 LT2 LT3 FR FR1 FR2 FR3 - location
		ABRUZZO CH CH1 CH2 CH3 PE PE1 PE2 PE3 TE TE1 TE2 TE3 AQ AQ1 AQ2 AQ3 AB1 AB11 AB12 AB13 AB2 AB21 AB22 AB23 - location
		MOLISE IS IS1 IS2 IS3 CB CB1 CB2 CB3 MO1 MO11 MO12 MO13 MO2 MO21 MO22 MO23 MO3 MO31 MO32 MO33 MO4 MO41 MO42 MO43 - location
		CAMPANIA NA NA1 NA2 NA3 CE CE1 CE2 CE3 AV AV1 AV2 AV3 BN BN1 BN2 BN3 CA1 CA11 CA12 CA13 CA2 CA21 CA22 CA23 - location
		BASILICATA MT MT1 MT2 MT3 PZ PZ1 PZ2 PZ3 BA1 BA11 BA12 BA13 BA2 BA21 BA22 BA23 BA3 BA31 BA32 BA33 BA4 BA41 BA42 BA43 - location
		PUGLIA FG FG1 FG2 FG3 BT BT1 BT2 BT3 BA BA1 BA2 BA3 TA TA1 TA2 TA3 BR BR1 BR2 BR3 LE LE1 LE2 LE3 - location
		CALABRIA CZ CZ1 CZ2 CZ3 KR KR1 KR2 KR3 CS CS1 CS2 CS3 VV VV1 VV2 VV3 RC RC1 RC2 RC3 RE1 RE11 RE12 RE13 - location
		SICILIA CT CT1 CT2 CT3 ME ME1 ME2 ME3 PA PA1 PA2 PA3 AG AG1 AG2 AG3 TP TP1 TP2 TP3 EN EN1 EN2 EN3 - location
		MARCHE PU PU1 PU2 PU3 AN AN1 AN2 AN3 MC MC1 MC2 MC3 AP AP1 AP2 AP3 FM FM1 FM2 FM3 MA1 MA11 MA12 MA13 - location
		UMBRIA PG PG1 PG2 PG3 TR TR1 TR2 TR3 UM1 UM11 UM12 UM13 UM2 UM21 UM22 UM23 UM3 UM31 UM32 UM33 UM4 UM41 UM42 UM43 - location 
		TOSCANA FI FI1 FI2 FI3 PI PI1 PI2 PI3 LI LI1 LI2 LI3 GR GR1 GR2 GR3 AR AR1 AR2 AR3 SI SI1 SI2 SI3 - location
		EMILIAROMAGNA BO BO1 BO2 BO3 FC FC1 FC2 FC3 PR PR1 PR2 PR3 RA RA1 RA2 RA3 MO MO1 MO2 MO3 FE FE1 FE2 FE3 PC PC1 PC2 PC3 - location
		VENETO VR VR1 VR2 VR3 VE VE1 VE2 VE3 VI VI1 VI2 VI3 BL BL1 BL2 BL3 PD PD1 PD2 PD3 TV TV1 TV2 TV3 - location
		LOMBARDIA MI MI1 MI2 MI3 MN MN1 MN2 MN3 BS BS1 BS2 BS3 BG BG1 BG2 BG3 LC LC1 LC2 LC3 PV PV1 PV2 PV3 - location
		PIEMONTE TO TO1 TO2 TO3 AL AL1 AL2 AL3 AT AT1 AT2 AT3 CN CN1 CN2 CN3 VC VC1 VC2 VC3 VB VB1 VB2 VB3 - location
		LIGURIA GE GE1 GE2 GE3 SP SP1 SP2 SP3 IM IM1 IM2 IM3 SV SV1 SV2 SV3 LI1 LI11 LI12 LI13 LI2 LI21 LI22 LI23 - location
		TRENTINO TRE TRE1 TRE2 TRE3 BZ BZ1 BZ2 BZ3 AA1 AA11 AA12 AA13 AA2 AA21 AA22 AA23 AA3 AA31 AA32 AA33 AA4 AA41 AA42 AA43 - location
		AOSTA AO1 AO11 AO12 AO13 AO2 AO21 AO22 AO23 AO3 AO31 AO32 AO33 AO4 AO41 AO42 AO43 AO5 AO51 AO52 AO53 AO6 AO61 AO62 AO63 - location
		FRIULI PN PN1 PN2 PN3 UD UD1 UD2 UD3 TS TS1 TS2 TS3 GO GO1 GO2 GO3 FRI1 FRI11 FRI12 FRI13 FRI2 FRI21 FRI22 FRI23 - location
		SARDEGNA CAG CAG1 CAG2 CAG3 NU NU1 NU2 NU3 ORI ORI1 ORI2 ORI3 SS SS1 SS2 SS3 SAR1 SAR11 SAR12 SAR13 SAR2 SAR21 SAR22 SAR23 - location 
	)
		
	(:init
;CAPACITIES
    ;LOCATIONS
    (= (capacity CENTRAL_VACC_POINT) 363)
    (= (capacity LAZIO) 0)
    (= (capacity RM) 0)
    (= (capacity RM1) 0)
    (= (capacity RM2) 0)    
    (= (capacity RM3) 0)
    (= (capacity VT) 0)
    (= (capacity VT1) 0)
    (= (capacity VT2) 0)
    (= (capacity VT3) 0)
    (= (capacity LZ1) 0)
    (= (capacity LZ11) 0)
    (= (capacity LZ12) 0)
    (= (capacity LZ13) 0)
    (= (capacity RI) 0)
    (= (capacity RI1) 0)
    (= (capacity RI2) 0)
    (= (capacity RI3) 0)
    (= (capacity LT) 0)
    (= (capacity LT1) 0)
    (= (capacity LT2) 0)
    (= (capacity LT3) 0)
    (= (capacity FR) 0)
    (= (capacity FR1) 0)
    (= (capacity FR2) 0)
    (= (capacity FR3) 0)
    (= (capacity ABRUZZO) 0)
    (= (capacity CH) 0)
    (= (capacity CH1) 0)
    (= (capacity CH2) 0)
    (= (capacity CH3) 0)
    (= (capacity PE) 0)
    (= (capacity PE1) 0)
    (= (capacity PE2) 0)
    (= (capacity PE3) 0)
    (= (capacity TE) 0)
    (= (capacity TE1) 0)
    (= (capacity TE2) 0)
    (= (capacity TE3) 0)
    (= (capacity AQ) 0)
    (= (capacity AQ1) 0)
    (= (capacity AQ2) 0)
    (= (capacity AQ3) 0)
    (= (capacity AB1) 0)
    (= (capacity AB11) 0)
    (= (capacity AB12) 0)
    (= (capacity AB13) 0)
    (= (capacity AB2) 0)
    (= (capacity AB21) 0)
    (= (capacity AB22) 0)
    (= (capacity AB23) 0)
    (= (capacity MOLISE) 0)
    (= (capacity IS) 0)
    (= (capacity IS1) 0)
    (= (capacity IS2) 0)
    (= (capacity IS3) 0)
    (= (capacity CB) 0)
    (= (capacity CB1) 0)
    (= (capacity CB2) 0)
    (= (capacity CB3) 0)
    (= (capacity MO1) 0)
    (= (capacity MO11) 0)
    (= (capacity MO12) 0)
    (= (capacity MO13) 0)
    (= (capacity MO2) 0)
    (= (capacity MO21) 0)
    (= (capacity MO22) 0)
    (= (capacity MO23) 0)
    (= (capacity MO3) 0)
    (= (capacity MO31) 0)
    (= (capacity MO32) 0)
    (= (capacity MO33) 0)
    (= (capacity MO4) 0)
    (= (capacity MO41) 0)
    (= (capacity MO42) 0)
    (= (capacity MO43) 0)
    (= (capacity CAMPANIA) 0)
    (= (capacity NA) 0)
    (= (capacity NA1) 0)
    (= (capacity NA2) 0)
    (= (capacity NA3) 0)
    (= (capacity CE) 0)
    (= (capacity CE1) 0)
    (= (capacity CE2) 0)
    (= (capacity CE3) 0)
    (= (capacity AV) 0)
    (= (capacity AV1) 0)
    (= (capacity AV2) 0)
    (= (capacity AV3) 0)
    (= (capacity BN) 0)
    (= (capacity BN1) 0)
    (= (capacity BN2) 0)
    (= (capacity BN3) 0)
    (= (capacity CA1) 0)
    (= (capacity CA11) 0)
    (= (capacity CA12) 0)
    (= (capacity CA13) 0)
    (= (capacity CA2) 0)
    (= (capacity CA21) 0)
    (= (capacity CA22) 0)
    (= (capacity CA23) 0)
    (= (capacity BASILICATA) 0)
    (= (capacity MT) 0)
    (= (capacity MT1) 0)
    (= (capacity MT2) 0)
    (= (capacity MT3) 0)
    (= (capacity PZ) 0)
    (= (capacity PZ1) 0)
    (= (capacity PZ2) 0)
    (= (capacity PZ3) 0)
    (= (capacity BA1) 0)
    (= (capacity BA11) 0)
    (= (capacity BA12) 0)
    (= (capacity BA13) 0)
    (= (capacity BA2) 0)
    (= (capacity BA21) 0)
    (= (capacity BA22) 0)
    (= (capacity BA23) 0)
    (= (capacity BA3) 0)
    (= (capacity BA31) 0)
    (= (capacity BA32) 0)
    (= (capacity BA33) 0)
    (= (capacity BA4) 0)
    (= (capacity BA41) 0)
    (= (capacity BA42) 0)
    (= (capacity BA43) 0)
    (= (capacity PUGLIA) 0)
    (= (capacity FG) 0)
    (= (capacity FG1) 0)
    (= (capacity FG2) 0)
    (= (capacity FG3) 0)
    (= (capacity BT) 0)
    (= (capacity BT1) 0)
    (= (capacity BT2) 0)
    (= (capacity BT3) 0)
    (= (capacity BA) 0)
    (= (capacity BA1) 0)
    (= (capacity BA2) 0)
    (= (capacity BA3) 0)
    (= (capacity TA) 0)
    (= (capacity TA1) 0)
    (= (capacity TA2) 0)
    (= (capacity TA3) 0)
    (= (capacity BR) 0)
    (= (capacity BR1) 0)
    (= (capacity BR2) 0)
    (= (capacity BR3) 0)
    (= (capacity LE) 0)
    (= (capacity LE1) 0)
    (= (capacity LE2) 0)
    (= (capacity LE3) 0)
    (= (capacity CALABRIA) 0)
    (= (capacity CZ) 0)
    (= (capacity CZ1) 0)
    (= (capacity CZ2) 0)
    (= (capacity CZ3) 0)
    (= (capacity KR) 0)
    (= (capacity KR1) 0)
    (= (capacity KR2) 0)
    (= (capacity KR3) 0)
    (= (capacity CS) 0)
    (= (capacity CS1) 0)
    (= (capacity CS2) 0)
    (= (capacity CS3) 0)
    (= (capacity VV) 0)
    (= (capacity VV1) 0)
    (= (capacity VV2) 0)
    (= (capacity VV3) 0)
    (= (capacity RC) 0)
    (= (capacity RC1) 0)
    (= (capacity RC2) 0)
    (= (capacity RC3) 0)
    (= (capacity RE1) 0)
    (= (capacity RE11) 0)
    (= (capacity RE12) 0)
    (= (capacity RE13) 0)
    (= (capacity SICILIA) 0)
    (= (capacity CT) 0)
    (= (capacity CT1) 0)
    (= (capacity CT2) 0)
    (= (capacity CT3) 0)
    (= (capacity ME) 0)
    (= (capacity ME1) 0)
    (= (capacity ME2) 0)
    (= (capacity ME3) 0)
    (= (capacity PA) 0)
    (= (capacity PA1) 0)
    (= (capacity PA2) 0)
    (= (capacity PA3) 0)
    (= (capacity AG) 0)
    (= (capacity AG1) 0)
    (= (capacity AG2) 0)
    (= (capacity AG3) 0)
    (= (capacity TP) 0)
    (= (capacity TP1) 0)
    (= (capacity TP2) 0)
    (= (capacity TP3) 0)
    (= (capacity EN) 0)
    (= (capacity EN1) 0)
    (= (capacity EN2) 0)
    (= (capacity EN3) 0)
    (= (capacity MARCHE) 0)
    (= (capacity PU) 0)
    (= (capacity PU1) 0)
    (= (capacity PU2) 0)
    (= (capacity PU3) 0)
    (= (capacity AN) 0)
    (= (capacity AN1) 0)
    (= (capacity AN2) 0)
    (= (capacity AN3) 0)
    (= (capacity MC) 0)
    (= (capacity MC1) 0)
    (= (capacity MC2) 0)
    (= (capacity MC3) 0)
    (= (capacity AP) 0)
    (= (capacity AP1) 0)
    (= (capacity AP2) 0)
    (= (capacity AP3) 0)
    (= (capacity FM) 0)
    (= (capacity FM1) 0)
    (= (capacity FM2) 0)
    (= (capacity FM3) 0)
    (= (capacity MA1) 0)
    (= (capacity MA11) 0)
    (= (capacity MA12) 0)
    (= (capacity MA13) 0)
    (= (capacity UMBRIA) 0)
    (= (capacity PG) 0)
    (= (capacity PG1) 0)
    (= (capacity PG2) 0)
    (= (capacity PG3) 0)
    (= (capacity TR) 0)
    (= (capacity TR1) 0)
    (= (capacity TR2) 0)
    (= (capacity TR3) 0)
    (= (capacity UM1) 0)
    (= (capacity UM11) 0)
    (= (capacity UM12) 0)
    (= (capacity UM13) 0)
    (= (capacity UM2) 0)
    (= (capacity UM21) 0)
    (= (capacity UM22) 0)
    (= (capacity UM23) 0)
    (= (capacity UM3) 0)
    (= (capacity UM31) 0)
    (= (capacity UM32) 0)
    (= (capacity UM33) 0)
    (= (capacity UM4) 0)
    (= (capacity UM41) 0)
    (= (capacity UM42) 0)
    (= (capacity UM43) 0)
    (= (capacity TOSCANA) 0)
    (= (capacity FI) 0)
    (= (capacity FI1) 0)
    (= (capacity FI2) 0)
    (= (capacity FI3) 0)
    (= (capacity PI) 0)
    (= (capacity PI1) 0)
    (= (capacity PI2) 0)
    (= (capacity PI3) 0)
    (= (capacity LI) 0)
    (= (capacity LI1) 0)
    (= (capacity LI2) 0)
    (= (capacity LI3) 0)
    (= (capacity GR) 0)
    (= (capacity GR1) 0)
    (= (capacity GR2) 0)
    (= (capacity GR3) 0)
    (= (capacity AR) 0)
    (= (capacity AR1) 0)
    (= (capacity AR2) 0)
    (= (capacity AR3) 0)
    (= (capacity SI) 0)
    (= (capacity SI1) 0)
    (= (capacity SI2) 0)
    (= (capacity SI3) 0)
    (= (capacity EMILIAROMAGNA) 0)
    (= (capacity BO) 0)
    (= (capacity BO1) 0)
    (= (capacity BO2) 0)
    (= (capacity BO3) 0)
    (= (capacity FC) 0)
    (= (capacity FC1) 0)
    (= (capacity FC2) 0)
    (= (capacity FC3) 0)
    (= (capacity PR) 0)
    (= (capacity PR1) 0)
    (= (capacity PR2) 0)
    (= (capacity PR3) 0)
    (= (capacity RA) 0)
    (= (capacity RA1) 0)
    (= (capacity RA2) 0)
    (= (capacity RA3) 0)
    (= (capacity MO) 0)
    (= (capacity MO1) 0)
    (= (capacity MO2) 0)
    (= (capacity MO3) 0)
    (= (capacity FE) 0)
    (= (capacity FE1) 0)
    (= (capacity FE2) 0)
    (= (capacity FE3) 0)
    (= (capacity PC) 0)
    (= (capacity PC1) 0)
    (= (capacity PC2) 0)
    (= (capacity PC3) 0)
    (= (capacity VENETO) 0)
    (= (capacity VR) 0)
    (= (capacity VR1) 0)
    (= (capacity VR2) 0)
    (= (capacity VR3) 0)
    (= (capacity VE) 0)
    (= (capacity VE1) 0)
    (= (capacity VE2) 0)
    (= (capacity VE3) 0)
    (= (capacity VI) 0)
    (= (capacity VI1) 0)
    (= (capacity VI2) 0)
    (= (capacity VI3) 0)
    (= (capacity BL) 0)
    (= (capacity BL1) 0)
    (= (capacity BL2) 0)
    (= (capacity BL3) 0)
    (= (capacity PD) 0)
    (= (capacity PD1) 0)
    (= (capacity PD2) 0)
    (= (capacity PD3) 0)
    (= (capacity TV) 0)
    (= (capacity TV1) 0)
    (= (capacity TV2) 0)
    (= (capacity TV3) 0)
    (= (capacity LOMBARDIA) 0)
    (= (capacity MI) 0)
    (= (capacity MI1) 0)
    (= (capacity MI2) 0)
    (= (capacity MI3) 0)
    (= (capacity MN) 0)
    (= (capacity MN1) 0)
    (= (capacity MN2) 0)
    (= (capacity MN3) 0)
    (= (capacity BS) 0)
    (= (capacity BS1) 0)
    (= (capacity BS2) 0)
    (= (capacity BS3) 0)
    (= (capacity BG) 0)
    (= (capacity BG1) 0)
    (= (capacity BG2) 0)
    (= (capacity BG3) 0)
    (= (capacity LC) 0)
    (= (capacity LC1) 0)
    (= (capacity LC2) 0)
    (= (capacityLC3) 0)
    (= (capacity PV) 0)
    (= (capacity PV1) 0)
    (= (capacity PV2) 0)
    (= (capacity PV3) 0)
    (= (capacity PIEMONTE) 0)
    (= (capacity TO) 0)
    (= (capacity TO1) 0)
    (= (capacity TO2) 0)
    (= (capacity TO3) 0)
    (= (capacity AL) 0)
    (= (capacity AL1) 0)
    (= (capacity AL2) 0)
    (= (capacity AL3) 0)
    (= (capacity AT) 0)
    (= (capacity AT1) 0)
    (= (capacity AT2) 0)
    (= (capacity AT3) 0)
    (= (capacity CN) 0)
    (= (capacity CN1) 0)
    (= (capacity CN2) 0)
    (= (capacity CN3) 0)
    (= (capacity VC) 0)
    (= (capacity VC1) 0)
    (= (capacity VC2) 0)
    (= (capacity VC3) 0)
    (= (capacity VB) 0)
    (= (capacity VB1) 0)
    (= (capacity VB2) 0)
    (= (capacity VB3) 0)
    (= (capacity LIGURIA) 0)
    (= (capacity GE) 0)
    (= (capacity GE1) 0)
    (= (capacity GE2) 0)
    (= (capacity GE3) 0)
    (= (capacity SP) 0)
    (= (capacity SP1) 0)
    (= (capacity SP2) 0)
    (= (capacity SP3) 0)
    (= (capacity IM) 0)
    (= (capacity IM1) 0)
    (= (capacity IM2) 0)
    (= (capacity IM3) 0)
    (= (capacity SV) 0)
    (= (capacity SV1) 0)
    (= (capacity SV2) 0)
    (= (capacity SV3) 0)
    (= (capacity LI1) 0)
    (= (capacity LI11) 0)
    (= (capacity LI12) 0)
    (= (capacity LI13) 0)
    (= (capacity LI2) 0)
    (= (capacity LI21) 0)
    (= (capacity LI22) 0)
    (= (capacity LI23) 0)
    (= (capacity TRENTINO) 0)
    (= (capacity TRE) 0)
    (= (capacity TRE1) 0)
    (= (capacity TRE2) 0)
    (= (capacity TRE3) 0)
    (= (capacity BZ) 0)
    (= (capacity BZ1) 0)
    (= (capacity BZ2) 0)
    (= (capacity BZ3) 0)
    (= (capacity AA1) 0)
    (= (capacity AA11) 0)
    (= (capacity AA12) 0)
    (= (capacity AA13) 0)
    (= (capacity AA2) 0)
    (= (capacity AA21) 0)
    (= (capacity AA22) 0)
    (= (capacity AA23) 0)
    (= (capacity AA3) 0)
    (= (capacity AA31) 0)
    (= (capacity AA32) 0)
    (= (capacity AA33) 0)
    (= (capacity AA4) 0)
    (= (capacity AA41) 0)
    (= (capacity AA42) 0)
    (= (capacity AA43) 0)
    (= (capacity AOSTA) 0)
    (= (capacity AO1) 0)
    (= (capacity AO11) 0)
    (= (capacity AO12) 0)
    (= (capacity AO13) 0)
    (= (capacity AO2) 0)
    (= (capacity AO21) 0)
    (= (capacity AO22) 0)
    (= (capacity AO23) 0)
    (= (capacity AO3) 0)
    (= (capacity AO31) 0)
    (= (capacity AO32) 0)
    (= (capacity AO33) 0)
    (= (capacity AO4) 0)
    (= (capacity AO41) 0)
    (= (capacity AO42) 0)
    (= (capacity AO43) 0)
    (= (capacity AO5) 0)
    (= (capacity AO51) 0)
    (= (capacity AO52) 0)
    (= (capacity AO53) 0)
    (= (capacity AO6) 0)
    (= (capacity AO61) 0)
    (= (capacity AO62) 0)
    (= (capacity AO63) 0)
    (= (capacity FRIULI) 0)
    (= (capacity PN) 0)
    (= (capacity PN1) 0)
    (= (capacity PN2) 0)
    (= (capacity PN3) 0)
    (= (capacity UD) 0)
    (= (capacity UD1) 0)
    (= (capacity UD2) 0)
    (= (capacity UD3) 0)
    (= (capacity TS) 0)
    (= (capacity TS1) 0)
    (= (capacity TS2) 0)
    (= (capacity TS3) 0)
    (= (capacity GO) 0)
    (= (capacity GO1) 0)
    (= (capacity GO2) 0)
    (= (capacity GO3) 0)
    (= (capacity FRI1) 0)
    (= (capacity FRI11) 0)
    (= (capacity FRI12) 0)
    (= (capacity FRI13) 0)
    (= (capacity FRI2) 0)
    (= (capacity FRI21) 0)
    (= (capacity FRI22) 0)
    (= (capacity FRI23) 0)
    (= (capacity SARDEGNA) 0)
    (= (capacity CAG) 0)
    (= (capacity CAG1) 0)
    (= (capacity CAG2) 0)
    (= (capacity CAG3) 0)
    (= (capacity NU) 0)
    (= (capacity NU1) 0)
    (= (capacity NU2) 0)
    (= (capacity NU3) 0)
    (= (capacity ORI) 0)
    (= (capacity ORI1) 0)
    (= (capacity ORI2) 0)
    (= (capacity ORI3) 0)
    (= (capacity SS) 0)
    (= (capacity SS1) 0)
    (= (capacity SS2) 0)
    (= (capacity SS3) 0)
    (= (capacity SAR1) 0)
    (= (capacity SAR11) 0)
    (= (capacity SAR12) 0)
    (= (capacity SAR13) 0)
    (= (capacity SAR2) 0)
    (= (capacity SAR21) 0)
    (= (capacity SAR22) 0)
    (= (capacity SAR23) 0)
    ;TRUCKS
    (= (capacity truck1) 0)  (= (capacity truck2) 0)  (= (capacity truck3) 0)  (= (capacity truck4) 0)  (= (capacity truck5) 0)  
    (= (capacity truck6) 0)  (= (capacity truck7) 0)  (= (capacity truck8) 0)  (= (capacity truck9) 0)  (= (capacity truck10) 0)  
    (= (capacity truck11) 0)  (= (capacity truck12) 0)  (= (capacity truck13) 0)  (= (capacity truck14) 0)  (= (capacity truck15) 0)  
    (= (capacity truck16) 0)  (= (capacity truck17) 0)  (= (capacity truck18) 0)  (= (capacity truck19) 0)  (= (capacity truck20) 0)  
    ;DRONES
    (= (capacity drone1) 0)
    (= (capacity drone2) 0)
    (= (capacity drone3) 0)
    (= (capacity drone4) 0)
    (= (capacity drone5) 0)
    (= (capacity drone6) 0)
    (= (capacity drone7) 0)
    (= (capacity drone8) 0)
    (= (capacity drone9) 0)
    (= (capacity drone10) 0)
    (= (capacity drone11) 0)
    (= (capacity drone12) 0)
    (= (capacity drone13) 0)
    (= (capacity drone14) 0)
    (= (capacity drone15) 0)
    (= (capacity drone16) 0)
    (= (capacity drone17) 0)
    (= (capacity drone18) 0)
    (= (capacity drone19) 0)
    (= (capacity drone20) 0)
    (= (capacity drone21) 0)
    (= (capacity drone22) 0)
    (= (capacity drone23) 0)
    (= (capacity drone24) 0)
    (= (capacity drone25) 0)
    (= (capacity drone26) 0)
    (= (capacity drone27) 0)
    (= (capacity drone28) 0)
    (= (capacity drone29) 0)
    (= (capacity drone30) 0)
    (= (capacity drone31) 0)
    (= (capacity drone32) 0)
    (= (capacity drone33) 0)
    (= (capacity drone34) 0)
    (= (capacity drone35) 0)
    (= (capacity drone36) 0)
    (= (capacity drone37) 0)
    (= (capacity drone38) 0)
    (= (capacity drone39) 0)
    (= (capacity drone40) 0)
    (= (capacity drone41) 0)
    (= (capacity drone42) 0)
    (= (capacity drone43) 0)
    (= (capacity drone44) 0)
    (= (capacity drone45) 0)
    (= (capacity drone46) 0)
    (= (capacity drone47) 0)
    (= (capacity drone48) 0)
    (= (capacity drone49) 0)
    (= (capacity drone50) 0)
    (= (capacity drone51) 0)
    (= (capacity drone52) 0)
    (= (capacity drone53) 0)
    (= (capacity drone54) 0)
    (= (capacity drone55) 0)
    (= (capacity drone56) 0)
    (= (capacity drone57) 0)
    (= (capacity drone58) 0)
    (= (capacity drone59) 0)
    (= (capacity drone60) 0)
    (= (capacity drone61) 0)
    (= (capacity drone62) 0)
    (= (capacity drone63) 0)
    (= (capacity drone64) 0)
    (= (capacity drone65) 0)
    (= (capacity drone66) 0)
    (= (capacity drone67) 0)
    (= (capacity drone68) 0)
    (= (capacity drone69) 0)
    (= (capacity drone70) 0)
    (= (capacity drone71) 0)
    (= (capacity drone72) 0)
    (= (capacity drone73) 0)
    (= (capacity drone74) 0)
    (= (capacity drone75) 0)
    (= (capacity drone76) 0)
    (= (capacity drone77) 0)
    (= (capacity drone78) 0)
    (= (capacity drone79) 0)
    (= (capacity drone80) 0)
    (= (capacity drone81) 0)
    (= (capacity drone82) 0)
    (= (capacity drone83) 0)
    (= (capacity drone84) 0)
    (= (capacity drone85) 0)
    (= (capacity drone86) 0)
    (= (capacity drone87) 0)
    (= (capacity drone88) 0)
    (= (capacity drone89) 0)
    (= (capacity drone90) 0)
    (= (capacity drone91) 0)
    (= (capacity drone92) 0)
    (= (capacity drone93) 0)
    (= (capacity drone94) 0)
    (= (capacity drone95) 0)
    (= (capacity drone96) 0)
    (= (capacity drone97) 0)
    (= (capacity drone98) 0)
    (= (capacity drone99) 0)
    (= (capacity drone100) 0)
    (= (capacity drone101) 0)
    (= (capacity drone102) 0)
    (= (capacity drone103) 0)
    (= (capacity drone104) 0)
    (= (capacity drone105) 0)
    (= (capacity drone106) 0)
    (= (capacity drone107) 0)
    (= (capacity drone108) 0)
    (= (capacity drone109) 0)
    (= (capacity drone110) 0)
    (= (capacity drone111) 0)
    (= (capacity drone112) 0)
    (= (capacity drone113) 0)
    (= (capacity drone114) 0)
    (= (capacity drone115) 0)
    (= (capacity drone116) 0)
    (= (capacity drone117) 0)
    (= (capacity drone118) 0)
    (= (capacity drone119) 0)
    (= (capacity drone120) 0)
    (= (capacity drone121) 0)
    ;PLANES
    (= (capacity plane1) 0)
    (= (capacity plane2) 0)
    (= (capacity plane3) 0)
    (= (capacity plane4) 0)
    (= (capacity plane5) 0)
    (= (capacity plane6) 0)
    (= (capacity plane7) 0)
    (= (capacity plane8) 0)
    (= (capacity plane9) 0)
    (= (capacity plane10) 0)
    

;;;CONNECTIONS
    ;;;REGION CONNECTIONS;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (connected LAZIO CENTRAL_VACC_POINT)
    (connected CENTRAL_VACC_POINT LAZIO)
    (connected CAMPANIA CENTRAL_VACC_POINT)
    (connected CENTRAL_VACC_POINT CAMPANIA)
    (connected ABRUZZO CENTRAL_VACC_POINT)
    (connected CENTRAL_VACC_POINT ABRUZZO)
    (connected MOLISE CENTRAL_VACC_POINT)
    (connected CENTRAL_VACC_POINT MOLISE)
    (connected LAZIO CAMPANIA)
    (connected CAMPANIA LAZIO)
    (connected CAMPANIA MOLISE)
    (connected MOLISE CAMPANIA)
    (connected MOLISE ABRUZZO)
    (connected ABRUZZO MOLISE)
    (connected ABRUZZO LAZIO)
    (connected LAZIO ABRUZZO)
    (connected MOLISE LAZIO)
    (connected LAZIO MOLISE)
    (connected CAMPANIA BASILICATA)
    (connected BASILICATA CAMPANIA)
    
    (connected CENTRAL_VACC_POINT LAZIO)
    (connected LAZIO CENTRAL_VACC_POINT)
    (connected LAZIO TOSCANA)
    (connected TOSCANA LAZIO)
    (connected LAZIO UMBRIA)
    (connected UMBRIA LAZIO)
    (connected LAZIO MARCHE)
    (connected MARCHE LAZIO)
    (connected LAZIO ABRUZZO)
    (connected ABRUZZO LAZIO)
    (connected LAZIO MOLISE)
    (connected MOLISE LAZIO)
    (connected LAZIO CAMPANIA)
    (connected CAMPANIA LAZIO)
    
    (connected ABRUZZO MOLISE)
    (connected MOLISE ABRUZZO)
    (connected ABRUZZO MARCHE)
    (connected MARCHE ABRUZZO)
    
    (connected MOLISE PUGLIA)
    (connected PUGLIA MOLISE)
    (connected MOLISE CAMPANIA)
    (connected CAMPANIA MOLISE)
    
    (connected CAMPANIA PUGLIA)
    (connected PUGLIA CAMPANIA)
    (connected CAMPANIA BASILICATA)
    (connected BASILICATA CAMPANIA)
    
    (connected BASILICATA PUGLIA)
    (connected PUGLIA BASILICATA)
    (connected BASILICATA CALABRIA)
    (connected CALABRIA BASILICATA)
    
    (connected MARCHE EMILIAROMAGNA)
    (connected EMILIAROMAGNA MARCHE)
    (connected MARCHE UMBRIA)
    (connected UMBRIA MARCHE)
    (connected MARCHE TOSCANA)
    (connected TOSCANA MARCHE)
    
    (connected UMBRIA TOSCANA)
    (connected TOSCANA UMBRIA)
    
    (connected TOSCANA EMILIAROMAGNA)
    (connected EMILIAROMAGNA TOSCANA)
    (connected TOSCANA LIGURIA)
    (connected LIGURIA TOSCANA)
    
    (connected EMILIAROMAGNA LOMBARDIA)
    (connected LOMBARDIA EMILIAROMAGNA)
    (connected EMILIAROMAGNA VENETO)
    (connected VENETO EMILIAROMAGNA)
    (connected EMILIAROMAGNA LIGURIA)
    (connected LIGURIA EMILIAROMAGNA)
    (connected EMILIAROMAGNA PIEMONTE)
    (connected PIEMONTE EMILIAROMAGNA)
    
    (connected VENETO TRENTINO)
    (connected TRENTINO VENETO)
    (connected VENETO FRIULI)
    (connected FRIULI VENETO)
    (connected VENETO LOMBARDIA)
    (connected LOMBARDIA VENETO)
    
    (connected LOMBARDIA TRENTINO)
    (connected TRENTINO LOMBARDIA)
    (connected LOMBARDIA PIEMONTE)
    (connected PIEMONTE LOMBARDIA)
    
    (connected PIEMONTE AOSTA)
    (connected AOSTA PIEMONTE)
    (connected PIEMONTE LIGURIA)
    (connected LIGURIA PIEMONTE)

    
    ;;;CONNECTINS FOR LAZIO
    (connected LAZIO VT)
    (connected VT LAZIO)
    (connected LAZIO RI)
    (connected RI LAZIO)
    (connected LAZIO RM)
    (connected RM LAZIO)
    (connected LAZIO LZ1)
    (connected LZ1 LAZIO)
    (connected LAZIO LT)
    (connected LT LAZIO)
    (connected LAZIO FR)
    (connected FR LAZIO)
        (connected VT VT1)
        (connected VT1 VT)
        (connected VT VT2)
        (connected VT2 VT)
        (connected VT VT3)
        (connected VT3 VT)
        (connected RM RM1)
        (connected RM1 RM)
        (connected RM RM2)
        (connected RM2 RM)
        (connected RM RM3)
        (connected RM3 RM)
        (connected LZ1 LZ11)
        (connected LZ11 LZ1)
        (connected LZ1 LZ12)
        (connected LZ12 LZ1)
        (connected LZ1 LZ13)
        (connected LZ13 LZ1)
        (connected LT LT1)
        (connected LT1 LT)
        (connected LT LT2)
        (connected LT2 LT)
        (connected LT LT3)
        (connected LT3 LT)
        (connected RI RI1)
        (connected RI1 RI)
        (connected RI RI2)
        (connected RI2 RI)
        (connected RI RI3)
        (connected RI3 RI)
        (connected FR FR1)
        (connected FR1 FR)
        (connected FR FR2)
        (connected FR2 FR)
        (connected FR FR3)
        (connected FR3 FR)
    
    ;;;CONNECTIONS FOR ABRUZZO
    (connected ABRUZZO TE)
    (connected TE ABRUZZO)
    (connected ABRUZZO AQ)
    (connected AQ ABRUZZO)
    (connected ABRUZZO PE)
    (connected PE ABRUZZO)
    (connected ABRUZZO CH)
    (connected CH ABRUZZO)
    (connected ABRUZZO AB1)
    (connected AB1 ABRUZZO)
    (connected ABRUZZO AB2)
    (connected AB2 ABRUZZO)
        (connected TE TE1)
        (connected TE1 TE)
        (connected TE TE2)
        (connected TE2 TE)
        (connected TE TE3)
        (connected TE3 TE)
        (connected AQ AQ1)
        (connected AQ1 AQ)
        (connected AQ AQ2)
        (connected AQ2 AQ)
        (connected AQ AQ3)
        (connected AQ3 AQ)
        (connected PE PE1)
        (connected PE1 PE)
        (connected PE PE2)
        (connected PE2 PE)
        (connected PE PE3)
        (connected PE3 TE)
        (connected CH CH1)
        (connected CH1 CH)
        (connected CH CH2)
        (connected CH2 CH)
        (connected CH CH3)
        (connected CH3 CH)
        (connected AB1 AB11)
        (connected AB11 AB1)
        (connected AB1 AB12)
        (connected AB12 AB1)
        (connected AB1 AB13)
        (connected AB13 AB1)
        (connected AB2 AB21)
        (connected AB21 AB2)
        (connected AB2 AB22)
        (connected AB22 AB2)
        (connected AB2 AB23)
        (connected AB23 AB2)
        (connected TE TE1)
        (connected TE1 TE)
        (connected TE TE2)
        (connected TE2 TE)
        (connected TE TE3)
        (connected TE3 TE)

    ;;;CONNECTIONS FOR MOLISE
    (connected MOLISE IS)
    (connected IS MOLISE)
    (connected MOLISE CB)
    (connected CB MOLISE)
    (connected MOLISE MO1)
    (connected MO1 MOLISE)
    (connected MOLISE MO2)
    (connected MO2 MOLISE)
    (connected MOLISE MO3)
    (connected MO3 MOLISE)
    (connected MOLISE MO4)
    (connected MO4 MOLISE)
        (connected IS IS1)
        (connected IS1 IS)
        (connected IS IS2)
        (connected IS2 IS)
        (connected IS IS3)
        (connected IS3 IS)
        (connected CB CB1)
        (connected CB1 CB)
        (connected CB CB2)
        (connected CB2 CB)
        (connected CB CB3)
        (connected CB3 CB)
        (connected MO1 MO11)
        (connected MO11 MO1)
        (connected MO1 MO12)
        (connected MO12 MO1)
        (connected MO1 MO13)
        (connected MO13 MO1)
        (connected MO2 MO21)
        (connected MO21 MO2)
        (connected MO2 MO22)
        (connected MO22 MO2)
        (connected MO2 MO23)
        (connected MO23 MO2)
        (connected MO3 MO31)
        (connected MO31 MO3)
        (connected MO3 MO32)
        (connected MO32 MO3)
        (connected MO3 MO33)
        (connected MO33 MO3)
        (connected MO4 MO41)
        (connected MO41 MO4)
        (connected MO4 MO42)
        (connected MO42 MO4)
        (connected MO4 MO43)
        (connected MO43 MO4)
        
    ;;;CONNECTIONS FOR CAMPANIA
    (connected CAMPANIA AV)
    (connected AV CAMPANIA)
    (connected CAMPANIA BN)
    (connected BN CAMPANIA)
    (connected CAMPANIA CE)
    (connected CE CAMPANIA)
    (connected CAMPANIA NA)
    (connected NA CAMPANIA)
    (connected CAMPANIA CA1)
    (connected CA1 CAMPANIA)
    (connected CAMPANIA CA2)
    (connected CA2 CAMPANIA)
        (connected AV AV1)
        (connected AV1 AV)
        (connected AV AV2)
        (connected AV2 AV)
        (connected AV AV3)
        (connected AV3 AV)
        (connected BN BN1)
        (connected BN1 BN)
        (connected BN BN2)
        (connected BN2 BN)
        (connected BN BN3)
        (connected BN3 BN)
        (connected CE CE1)
        (connected CE1 CE)
        (connected CE CE2)
        (connected CE2 CE)
        (connected CE CE3)
        (connected CE3 CE)
        (connected NA NA1)
        (connected NA1 NA)
        (connected NA NA2)
        (connected NA2 NA)
        (connected NA NA3)
        (connected NA3 NA)
        (connected CA1 CA11)
        (connected CA11 CA1)
        (connected CA1 CA12)
        (connected CA12 CA1)
        (connected CA1 CA13)
        (connected CA13 CA1)
        (connected CA2 CA21)
        (connected CA21 CA2)
        (connected CA2 CA22)
        (connected CA22 CA2)
        (connected CA2 CA23)
        (connected CA23 CA2)
        
    ;;;CONNECTIONS FOR BASILICATA
    (connected BASILICATA MT)
    (connected MT BASILICATA)
    (connected BASILICATA PZ)
    (connected PZ BASILICATA)
    (connected BASILICATA BA1)
    (connected BA1 BASILICATA)
    (connected BASILICATA BA2)
    (connected BA2 BASILICATA)
    (connected BASILICATA BA3)
    (connected BA3 BASILICATA)
    (connected BASILICATA BA4)
    (connected BA4 BASILICATA)
        (connected MT MT1)
        (connected MT1 MT)
        (connected MT MT2)
        (connected MT2 MT)
        (connected MT MT3)
        (connected MT3 MT)
        (connected PZ PZ1)
        (connected PZ1 PZ)
        (connected PZ PZ2)
        (connected PZ2 PZ)
        (connected PZ PZ3)
        (connected PZ3 PZ)
        (connected BA1 BA11)
        (connected BA11 BA1)
        (connected BA1 BA12)
        (connected BA12 BA1)
        (connected BA1 BA13)
        (connected BA13 BA1)
        (connected BA2 BA21)
        (connected BA21 BA2)
        (connected BA2 BA22)
        (connected BA22 BA2)
        (connected BA2 BA23)
        (connected BA23 BA2)
        (connected BA3 BA31)
        (connected BA31 BA3)
        (connected BA3 BA32)
        (connected BA32 BA3)
        (connected BA3 BA33)
        (connected BA33 BA31)
        (connected BA4 BA41)
        (connected BA41 BA4)
        (connected BA4 BA42)
        (connected BA42 BA4)
        (connected BA4 BA43)
        (connected BA43 BA4)
        
    ;CONNECTIONS FOR PUGLIA
    (connected PUGLIA FG)
    (connected FG PUGLIA)
    (connected PUGLIA BT)
    (connected BT PUGLIA)
    (connected PUGLIA BA)
    (connected BA PUGLIA)
    (connected PUGLIA TA)
    (connected TA PUGLIA)
    (connected PUGLIA BR)
    (connected BR PUGLIA)
    (connected PUGLIA LE)
    (connected LE PUGLIA)
        (connected FG FG1)
        (connected FG1 FG)
        (connected FG FG2)
        (connected FG2 FG)
        (connected FG FG3)
        (connected FG3 FG)
        (connected BT BT1)
        (connected BT1 BT)
        (connected BT BT2)
        (connected BT2 BT)
        (connected BT BT3)
        (connected BT3 BT)
        (connected BA BA1)
        (connected BA1 BA)
        (connected BA BA2)
        (connected BA2 BA)
        (connected BA BA3)
        (connected BA3 BA)
        (connected TE TE1)
        (connected TE1 TE)
        (connected TE TE2)
        (connected TE2 TE)
        (connected TE TE3)
        (connected TE3 TE)
        (connected BR BR1)
        (connected BR1 BR)
        (connected BR BR2)
        (connected BR2 BR)
        (connected BR BR3)
        (connected BR3 BR)
        (connected LE LE1)
        (connected LE1 LE)
        (connected LE LE2)
        (connected LE2 LE)
        (connected LE LE3)
        (connected LE3 LE)
        
    ;;;CONNECTIONS FOR CALABRIA
    (connected CALABRIA CZ)
    (connected CZ CALABRIA)
    (connected CALABRIA KR)
    (connected KR CALABRIA)
    (connected CALABRIA CS)
    (connected CS CALABRIA)
    (connected CALABRIA VV)
    (connected VV CALABRIA)
    (connected CALABRIA RC)
    (connected RC CALABRIA)
    (connected CALABRIA RE1)
    (connected RE1 CALABRIA)
        (connected CZ CZ1)
        (connected CZ1 CZ)
        (connected CZ CZ2)
        (connected CZ2 CZ)
        (connected CZ CZ3)
        (connected CZ3 CZ)
        (connected KR KR1)
        (connected KR1 KR)
        (connected KR KR2)
        (connected KR2 KR)
        (connected KR KR3)
        (connected KR3 KR)
        (connected CS CS1)
        (connected CS1 CS)
        (connected CS CS2)
        (connected CS2 CS)
        (connected CS CS3)
        (connected CS3 CS)
        (connected VV VV1)
        (connected VV1 VV)
        (connected VV VV2)
        (connected VV2 VV)
        (connected VV VV3)
        (connected VV3 VV)
        (connected RC RC1)
        (connected RC1 RC)
        (connected RC RC2)
        (connected RC2 RC)
        (connected RC RC3)
        (connected RC3 RC)
        (connected RE1 RE11)
        (connected RE11 RE1)
        (connected RE1 RE12)
        (connected RE12 RE1)
        (connected RE1 RE13)
        (connected RE13 RE1)
        
    ;;;CONNECTIONS FOR SICILIA
    (connected SICILIA CT)
    (connected CT SICILIA)
    (connected SICILIA ME)
    (connected ME SICILIA)
    (connected SICILIA PA)
    (connected PA SICILIA)
    (connected SICILIA AG)
    (connected AG SICILIA)
    (connected SICILIA TP)
    (connected TP SICILIA)
    (connected SICILIA EN)
    (connected EN SICILIA)
        (connected CT CT1)
        (connected CT1 CT)
        (connected CT CT2)
        (connected CT2 CT)
        (connected CT CT3)
        (connected CT3 CT)
        (connected ME ME1)
        (connected ME1 ME)
        (connected ME ME2)
        (connected ME2 ME)
        (connected ME ME3)
        (connected ME3 ME)
        (connected PA PA1)
        (connected PA1 PA)
        (connected PA PA2)
        (connected PA2 PA)
        (connected PA PA3)
        (connected PA3 PA)
        (connected AG AG1)
        (connected AG1 AG)
        (connected AG AG2)
        (connected AG2 AG)
        (connected AG AG3)
        (connected AG3 AG)
        (connected TP TP1)
        (connected TP1 TP)
        (connected TP TP2)
        (connected TP2 TP)
        (connected TP TP3)
        (connected TP3 TP)
        (connected EN EN1)
        (connected EN1 EN)
        (connected EN EN2)
        (connected EN2 EN)
        (connected EN EN3)
        (connected EN3 EN)

    ;;;CONNECTIONS FOR MARCHE
    (connected MARCHE PU)
    (connected PU MARCHE)
    (connected MARCHE AN)
    (connected AN MARCHE)
    (connected MARCHE MC)
    (connected MC MARCHE)
    (connected MARCHE AP)
    (connected AP MARCHE)
    (connected MARCHE FM)
    (connected FM MARCHE)
    (connected MARCHE MA1)
    (connected MA1 MARCHE)
        (connected PU PU1)
        (connected PU1 PU)
        (connected PU PU2)
        (connected PU2 PU)
        (connected PU PU3)
        (connected PU3 PU)
        (connected AN AN1)
        (connected AN1 AN)
        (connected AN AN2)
        (connected AN2 AN)
        (connected AN AN3)
        (connected AN3 AN)
        (connected MC MC1)
        (connected MC1 MC)
        (connected MC MC2)
        (connected MC2 MC)
        (connected MC MC3)
        (connected MC3 MC)
        (connected AP AP1)
        (connected AP1 AP)
        (connected AP AP2)
        (connected AP2 AP)
        (connected AP AP3)
        (connected AP3 AP)
        (connected FM FM1)
        (connected FM1 FM)
        (connected FM FM2)
        (connected FM2 FM)
        (connected FM FM3)
        (connected FM3 FM)
        (connected MA1 MA11)
        (connected MA11 MA1)
        (connected MA1 MA12)
        (connected MA12 MA1)
        (connected MA1 MA13)
        (connected MA13 MA1)
        
    ;;;CONNECTIONS FOR UMBRIA
    (connected UMBRIA PG)
    (connected PG UMBRIA)
    (connected UMBRIA TR)
    (connected TR UMBRIA)
    (connected UMBRIA UM1)
    (connected UM1 UMBRIA)
    (connected UMBRIA UM2)
    (connected UM2 UMBRIA)
    (connected UMBRIA UM3)
    (connected UM3 UMBRIA)
    (connected UMBRIA UM4)
    (connected UM4 UMBRIA)
        (connected PG PG1)
        (connected PG1 PG)
        (connected PG PG2)
        (connected PG2 PG)
        (connected PG PG3)
        (connected PG3 PG)
        (connected TR TR1)
        (connected TR1 TR)
        (connected TR TR2)
        (connected TR2 TR)
        (connected TR TR3)
        (connected TR3 TR)
        (connected UM1 UM11)
        (connected UM11 UM1)
        (connected UM1 UM12)
        (connected UM12 UM1)
        (connected UM1 UM13)
        (connected UM13 UM1)
        (connected UM2 UM21)
        (connected UM21 UM2)
        (connected UM2 UM22)
        (connected UM22 UM2)
        (connected UM2 UM23)
        (connected UM23 UM2)
        (connected UM3 UM31)
        (connected UM31 UM3)
        (connected UM3 UM32)
        (connected UM32 UM3)
        (connected UM3 UM33)
        (connected UM33 UM3)
        (connected UM4 UM41)
        (connected UM41 UM4)
        (connected UM4 UM42)
        (connected UM42 UM4)
        (connected UM4 UM43)
        (connected UM43 UM4)

    ;;;CONNECTIONS FOR TOSCANA
    (connected TOSCANA FI)
    (connected FI TOSCANA)
    (connected TOSCANA PI)
    (connected PI TOSCANA)
    (connected TOSCANA LI)
    (connected LI TOSCANA)
    (connected TOSCANA GR)
    (connected GR TOSCANA)
    (connected TOSCANA AR)
    (connected AR TOSCANA)
    (connected TOSCANA SI)
    (connected SI TOSCANA)
        (connected FI FI1)
        (connected FI1 FI)
        (connected FI FI2)
        (connected FI2 FI)
        (connected FI FI3)
        (connected FI3 FI)
        (connected PI PI1)
        (connected PI1 PI)
        (connected PI PI2)
        (connected PI2 PI)
        (connected PI PI3)
        (connected PI3 PI)
        (connected LI LI1)
        (connected LI1 LI)
        (connected LI LI2)
        (connected LI2 LI)
        (connected LI LI3)
        (connected LI3 LI)
        (connected GR GR1)
        (connected GR1 GR)
        (connected GR GR2)
        (connected GR2 GR)
        (connected GR GR3)
        (connected GR3 GR)
        (connected AR AR1)
        (connected AR1 AR)
        (connected AR AR2)
        (connected AR2 AR)
        (connected AR AR3)
        (connected AR3 AR)
        (connected SI SI1)
        (connected SI1 SI)
        (connected SI SI2)
        (connected SI2 SI)
        (connected SI SI3)
        (connected SI3 SI)

    ;;;CONNECTIONS FOR EMILIAROMAGNA
    (connected EMILIAROMAGNA BO)
    (connected BO EMILIAROMAGNA)
    (connected EMILIAROMAGNA FC)
    (connected FC EMILIAROMAGNA)
    (connected EMILIAROMAGNA PR)
    (connected PR EMILIAROMAGNA)
    (connected EMILIAROMAGNA RA)
    (connected RA EMILIAROMAGNA)
    (connected EMILIAROMAGNA MO)
    (connected MO EMILIAROMAGNA)
    (connected EMILIAROMAGNA FE)
    (connected FE EMILIAROMAGNA)
    (connected EMILIAROMAGNA PC)
    (connected PC EMILIAROMAGNA)
        (connected BO BO1)
        (connected BO1 BO)
        (connected BO BO2)
        (connected BO2 BO)
        (connected BO BO3)
        (connected BO3 BO)
        (connected FC FC1)
        (connected FC1 FC)
        (connected FC FC2)
        (connected FC2 FC)
        (connected FC FC3)
        (connected FC3 FC)
        (connected PR PR1)
        (connected PR1 PR)
        (connected PR PR2)
        (connected PR2 PR)
        (connected PR PR3)
        (connected PR3 PR)
        (connected RA RA1)
        (connected RA1 RA)
        (connected RA RA2)
        (connected RA2 RA)
        (connected RA RA3)
        (connected RA3 RA)
        (connected MO MO1)
        (connected MO1 MO)
        (connected MO MO2)
        (connected MO2 MO)
        (connected MO MO3)
        (connected MO3 MO)
        (connected FE FE1)
        (connected FE1 FE)
        (connected FE FE2)
        (connected FE2 FE)
        (connected FE FE3)
        (connected FE3 FE)
        (connected PC PC1)
        (connected PC1 PC)
        (connected PC PC2)
        (connected PC2 PC)
        (connected PC PC3)
        (connected PC3 PC)

    ;;;CONNECTIONS FOR VENETO
    (connected VENETO VR)
    (connected VR VENETO)
    (connected VENETO VE)
    (connected VE VENETO)
    (connected VENETO VI)
    (connected VI VENETO)
    (connected VENETO BL)
    (connected BL VENETO)
    (connected VENETO PD)
    (connected PD VENETO)
    (connected VENETO TV)
    (connected TV VENETO)
        (connected VR VR1)
        (connected VR1 VR)
        (connected VR VR2)
        (connected VR2 VR)
        (connected VR VR3)
        (connected VR3 VR)
        (connected VE VE1)
        (connected VE1 VE)
        (connected VE VE2)
        (connected VE2 VE)
        (connected VE VE3)
        (connected VE3 VE)
        (connected VI VI1)
        (connected VI1 VI)
        (connected VI VI2)
        (connected VI2 VI)
        (connected VI VI3)
        (connected VI3 VI)
        (connected BL BL1)
        (connected BL1 BL)
        (connected BL BL2)
        (connected BL2 BL)
        (connected BL BL3)
        (connected BL3 BL)
        (connected PD PD1)
        (connected PD1 PD)
        (connected PD PD2)
        (connected PD2 PD)
        (connected PD PD3)
        (connected PD3 PD)
        (connected TV TV1)
        (connected TV1 TV)
        (connected TV TV2)
        (connected TV2 TV)
        (connected TV TV3)
        (connected TV3 TV)
        
    ;;;LOMBARDIA
    (connected LOMBARDIA MI)
    (connected MI LOMBARDIA)
    (connected LOMBARDIA MN)
    (connected MN LOMBARDIA)
    (connected LOMBARDIA BS)
    (connected BS LOMBARDIA)
    (connected LOMBARDIA BG)
    (connected BG LOMBARDIA)
    (connected LOMBARDIA LC)
    (connected LC LOMBARDIA)
    (connected LOMBARDIA PV)
    (connected PV LOMBARDIA)
        (connected MI MI1)
        (connected MI1 MI)
        (connected MI MI2)
        (connected MI2 MI)
        (connected MI MI3)
        (connected MI3 MI)
        (connected MN MN1)
        (connected MN1 MN)
        (connected MN MN2)
        (connected MN2 MN)
        (connected MN MN3)
        (connected MN3 MN)
        (connected BS BS1)
        (connected BS1 BS)
        (connected BS BS2)
        (connected BS2 BS)
        (connected BS BS3)
        (connected BS3 BS)
        (connected BG BG1)
        (connected BG1 BG)
        (connected BG BG2)
        (connected BG2 BG)
        (connected BG BG3)
        (connected BG3 BG)
        (connected LC LC1)
        (connected LC1 LC)
        (connected LC LC2)
        (connected LC2 LC)
        (connected LC LC3)
        (connected LC3 LC)
        (connected PV PV1)
        (connected PV1 PV)
        (connected PV PV2)
        (connected PV2 PV)
        (connected PV PV3)
        (connected PV3 PV)

    ;;;CONNECTIONS FOR PIEMONTE
    (connected PIEMONTE TO)
    (connected TO PIEMONTE)
    (connected PIEMONTE AL)
    (connected AL PIEMONTE)
    (connected PIEMONTE AT)
    (connected AT PIEMONTE)
    (connected PIEMONTE CN)
    (connected CN PIEMONTE)
    (connected PIEMONTE VC)
    (connected VC PIEMONTE)
    (connected PIEMONTE VB)
    (connected VB PIEMONTE)
        (connected TO TO1)
        (connected TO1 TO)
        (connected TO TO2)
        (connected TO2 TO)
        (connected TO TO3)
        (connected TO3 TO)
        (connected AL AL1)
        (connected AL1 AL)
        (connected AL AL2)
        (connected AL2 AL)
        (connected AL AL3)
        (connected AL3 AL)
        (connected AT AT1)
        (connected AT1 AT)
        (connected AT AT2)
        (connected AT2 AT)
        (connected AT AT3)
        (connected AT3 AT)
        (connected CN CN1)
        (connected CN1 CN)
        (connected CN CN2)
        (connected CN2 CN)
        (connected CN CN3)
        (connected CN3 CN)
        (connected VC VC1)
        (connected VC1 VC)
        (connected VC VC2)
        (connected VC2 VC)
        (connected VC VC3)
        (connected VC3 VC)
        (connected VB VB1)
        (connected VB1 VB)
        (connected VB VB2)
        (connected VB2 VB)
        (connected VB VB3)
        (connected VB3 VB)
        
    ;;;CONNECTIONS FOR LIGURIA
    (connected LIGURIA GE)
    (connected GE LIGURIA)
    (connected LIGURIA SP)
    (connected SP LIGURIA)
    (connected LIGURIA IM)
    (connected IM LIGURIA)
    (connected LIGURIA SV)
    (connected SV LIGURIA)
    (connected LIGURIA LI1)
    (connected LI1 LIGURIA)
    (connected LIGURIA LI2)
    (connected LI2 LIGURIA)
        (connected GE GE1)
        (connected GE1 GE)
        (connected GE GE2)
        (connected GE2 GE)
        (connected GE GE3)
        (connected GE3 GE)
        (connected SP SP1)
        (connected SP1 SP)
        (connected SP SP2)
        (connected SP2 SP)
        (connected SP SP3)
        (connected SP3 SP)
        (connected IM IM1)
        (connected IM1 IM)
        (connected IM IM2)
        (connected IM2 IM)
        (connected IM IM3)
        (connected IM3 IM)
        (connected SV SV1)
        (connected SV1 SV)
        (connected SV SV2)
        (connected SV2 SV)
        (connected SV SV3)
        (connected SV3 SV)
        (connected LI1 LI11)
        (connected LI11 LI1)
        (connected LI1 LI12)
        (connected LI12 LI1)
        (connected LI1 LI13)
        (connected LI13 LI1)
        (connected LI2 LI21)
        (connected LI21 LI2)
        (connected LI2 LI22)
        (connected LI22 LI2)
        (connected LI2 LI23)
        (connected LI23 LI2)
        
    ;;;CONNECTIONS FOR TRENTINO
    (connected TRENTINO TRE)
    (connected TRE TRENTINO)
    (connected TRENTINO BZ)
    (connected BZ TRENTINO)
    (connected TRENTINO AA1)
    (connected AA1 TRENTINO)
    (connected TRENTINO AA2)
    (connected AA2 TRENTINO)
    (connected TRENTINO AA3)
    (connected AA3 TRENTINO)
    (connected TRENTINO AA4)
    (connected AA4 TRENTINO)
        (connected TRE TRE1)
        (connected TRE1 TRE)
        (connected TRE TRE2)
        (connected TRE2 TRE)
        (connected TRE TRE3)
        (connected TRE3 TRE)
        (connected BZ BZ1)
        (connected BZ1 BZ)
        (connected BZ BZ2)
        (connected BZ2 BZ)
        (connected BZ BZ3)
        (connected BZ3 BZ)
        (connected AA1 AA11)
        (connected AA11 AA1)
        (connected AA1 AA12)
        (connected AA12 AA1)
        (connected AA1 AA13)
        (connected AA13 AA1)
        (connected AA2 AA21)
        (connected AA21 AA2)
        (connected AA2 AA22)
        (connected AA22 AA2)
        (connected AA2 AA23)
        (connected AA23 AA2)
        (connected AA3 AA31)
        (connected AA31 AA3)
        (connected AA3 AA32)
        (connected AA32 AA3)
        (connected AA3 AA33)
        (connected AA33 AA3)
        (connected AA4 AA41)
        (connected AA41 AA42)
        (connected AA4 AA42)
        (connected AA42 AA4)
        (connected AA4 AA43)
        (connected AA43 AA4)
        
    ;;;CONNECTIONS FOR AOSTA
    (connected AOSTA AO1)
    (connected AO1 AOSTA)
    (connected AOSTA AO2)
    (connected AO2 AOSTA)
    (connected AOSTA AO3)
    (connected AO3 AOSTA)
    (connected AOSTA AO4)
    (connected AO4 AOSTA)
    (connected AOSTA AO5)
    (connected AO5 AOSTA)
    (connected AOSTA AO6)
    (connected AO6 AOSTA)
        (connected AO1 AO11)
        (connected AO11 AO1)
        (connected AO1 AO12)
        (connected AO12 AO1)
        (connected AO1 AO13)
        (connected AO13 AO1)
        (connected AO2 AO21)
        (connected AO21 AO2)
        (connected AO2 AO22)
        (connected AO22 AO2)
        (connected AO2 AO23)
        (connected AO23 AO2)
        (connected AO3 AO31)
        (connected AO31 AO3)
        (connected AO3 AO32)
        (connected AO32 AO3)
        (connected AO3 AO33)
        (connected AO33 AO3)
        (connected AO4 AO41)
        (connected AO41 AO4)
        (connected AO4 AO42)
        (connected AO42 AO4)
        (connected AO4 AO43)
        (connected AO43 AO4)
        (connected AO5 AO51)
        (connected AO51 AO5)
        (connected AO5 AO52)
        (connected AO52 AO5)
        (connected AO5 AO53)
        (connected AO53 AO5)
        (connected AO6 AO61)
        (connected AO61 AO62)
        (connected AO6 AO62)
        (connected AO62 AO6)
        (connected AO6 AO63)
        (connected AO63 AO6)

    ;;;CONNECTIONS FOR FRIULI
    (connected FRIULI PN)
    (connected PN FRIULI)
    (connected FRIULI UD)
    (connected UD FRIULI)
    (connected FRIULI TS)
    (connected TS FRIULI)
    (connected FRIULI GO)
    (connected GO FRIULI)
    (connected FRIULI FRI1)
    (connected FRI1 FRIULI)
    (connected FRIULI FRI2)
    (connected FRI2 FRIULI)
        (connected PN PN1)
        (connected PN1 PN)
        (connected PN PN2)
        (connected PN2 PN)
        (connected PN PN3)
        (connected PN3 PN)
        (connected UD UD1)
        (connected UD1 UD)
        (connected UD UD2)
        (connected UD2 UD2)
        (connected UD UD3)
        (connected UD3 UD)
        (connected TS TS1)
        (connected TS1 TS)
        (connected TS TS2)
        (connected TS2 TS)
        (connected TS TS3)
        (connected TS3 TS)
        (connected GO GO1)
        (connected GO1 GO)
        (connected GO GO2)
        (connected GO2 GO)
        (connected GO GO3)
        (connected GO3 GO)
        (connected FRI1 FRI11)
        (connected FRI11 FRI1)
        (connected FRI1 FRI12)
        (connected FRI12 FRI1)
        (connected FRI1 FRI13)
        (connected FRI13 FRI1)
        (connected FRI2 FRI21)
        (connected FRI21 FRI2)
        (connected FRI2 FRI22)
        (connected FRI22 FRI2)
        (connected FRI2 FRI23)
        (connected FRI23 FRI2)     
        
    ;;;CONNECTIONS FOR SARDEGNA
    (connected SARDEGNA CAG)
    (connected CAG SARDEGNA)
    (connected SARDEGNA NU)
    (connected NU SARDEGNA)
    (connected SARDEGNA ORI)
    (connected ORI SARDEGNA)
    (connected SARDEGNA SS)
    (connected SS SARDEGNA)
    (connected SARDEGNA SAR1)
    (connected SAR1 SARDEGNA)
    (connected SARDEGNA SAR2)
    (connected SAR2 SARDEGNA)
        (connected CAG CAG1)
        (connected CAG1 CAG)
        (connected CAG CAG2)
        (connected CAG2 CAG)
        (connected CAG CAG3)
        (connected CAG3 CAG)
        (connected NU NU1)
        (connected NU1 NU)
        (connected NU NU2)
        (connected NU2 NU2)
        (connected NU NU3)
        (connected NU3 NU)
        (connected ORI ORI1)
        (connected ORI1 ORI)
        (connected ORI ORI2)
        (connected ORI2 ORI)
        (connected ORI ORI3)
        (connected ORI3 ORI)
        (connected SS SS1)
        (connected SS1 SS)
        (connected SS SS2)
        (connected SS2 SS)
        (connected SS SS3)
        (connected SS3 SS)
        (connected SAR1 SAR11)
        (connected SAR11 SAR1)
        (connected SAR1 SAR12)
        (connected SAR12 SAR1)
        (connected SAR1 SAR13)
        (connected SAR13 SAR1)
        (connected SAR2 SAR21)
        (connected SAR21 SAR2)
        (connected SAR2 SAR22)
        (connected SAR22 SAR2)
        (connected SAR2 SAR23)
        (connected SAR23 SAR2)   
        
    
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;declare provinces with airport
    (hasAirport RM) ;lazio
    (hasAirport MI) ;lombardia
    (hasAirport BG) ;lombardia
    (hasAirport CT) ;sicilia
    (hasAirport PA) ;sicilia
    (hasAirport BO) ;emiliaromagna
    (hasAirport VE) ;veneto
    (hasAirport CA) ;sardegna
    (hasAirport NA) ;campania
    (hasAirport BR) ;puglia
    (hasAirport CZ) ;calabria
    (hasAirport TO) ;piemonte
    (hasAirport PI) ;toscana
    (hasAirport ORI) ;sardegna
    (hasAirport VR) ;veneto
    (hasAirport GE) ;liguria
    (hasAirport TS) ;friuli
    (hasAirport FI) ;toscana
    (hasAirport PR) ;emiliaromagna
    (hasAirport PE) ;abruzzo
    (hasAirport BZ) ;trentino
    (hasAirport FG) ;puglia
    
	    
    ;DEFINE REGIONS
	    (is-region LAZIO)
	    (is-region ABRUZZO)
	    (is-region MOLISE)
	    (is-region CAMPANIA)
	    (is-region BASILICATA)
	    (is-region PUGLIA)
	    (is-region CALABRIA)
	    (is-region SICILIA)
	    (is-region MARCHE)
	    (is-region UMBRIA)
	    (is-region TOSCANA)
	    (is-region EMILIAROMAGNA)
	    (is-region VENETO)
	    (is-region LOMBARDIA)
	    (is-region PIEMONTE)
	    (is-region LIGURIA)
	    (is-region TRENTINO)
	    (is-region AOSTA)
	    (is-region FRIULI)
	    (is-region SARDEGNA)
	    
    ;WHAT IS HEALTH DISTRICT
        ;LAZIO
	    (is-hd RM1)
        (is-hd RM2)
        (is-hd RM3)
        (is-hd VT1)
        (is-hd VT2)
        (is-hd VT3)
        (is-hd LZ11)
        (is-hd LZ12)
        (is-hd LZ13)
        (is-hd RI1)
        (is-hd RI2)
        (is-hd RI3)
        (is-hd LT1)
        (is-hd LT2)
        (is-hd LT3)
        (is-hd FR1)
        (is-hd FR2)
        (is-hd FR3)
        (is-hd CH1)
        (is-hd CH2)
        (is-hd CH3)
        (is-hd PE1)
        (is-hd PE2)
        (is-hd PE3)
        (is-hd TE1)
        (is-hd TE2)
        (is-hd TE3)
        (is-hd AQ1)
        (is-hd AQ2)
        (is-hd AQ3)
        (is-hd AB11)
        (is-hd AB12)
        (is-hd AB13)
        (is-hd AB21)
        (is-hd AB22)
        (is-hd AB23)
        (is-hd IS1)
        (is-hd IS2)
        (is-hd IS3)
        (is-hd CB1)
        (is-hd CB2)
        (is-hd CB3)
        (is-hd MO11)
        (is-hd MO12)
        (is-hd MO13)
        (is-hd MO21)
        (is-hd MO22)
        (is-hd MO23)
        (is-hd MO31)
        (is-hd MO32)
        (is-hd MO33)
        (is-hd MO41)
        (is-hd MO42)
        (is-hd MO43)
        (is-hd NA1)
        (is-hd NA2)
        (is-hd NA3)
        (is-hd CE1)
        (is-hd CE2)
        (is-hd CE3)
        (is-hd AV1)
        (is-hd AV2)
        (is-hd AV3)
        (is-hd BN1)
        (is-hd BN2)
        (is-hd BN3)
        (is-hd CA11)
        (is-hd CA12)
        (is-hd CA13)
        (is-hd CA21)
        (is-hd CA22)
        (is-hd CA23)
        (is-hd MT1)
        (is-hd MT2)
        (is-hd MT3)
        (is-hd PZ1)
        (is-hd PZ2)
        (is-hd PZ3)
        (is-hd BA11)
        (is-hd BA12)
        (is-hd BA13)
        (is-hd BA21)
        (is-hd BA22)
        (is-hd BA23)
        (is-hd BA31)
        (is-hd BA32)
        (is-hd BA33)
        (is-hd BA41)
        (is-hd BA42)
        (is-hd BA43)
        (is-hd FG1)
        (is-hd FG2)
        (is-hd FG3)
        (is-hd BT1)
        (is-hd BT2)
        (is-hd BT3)
        (is-hd BA1)
        (is-hd BA2)
        (is-hd BA3)
        (is-hd TA1)
        (is-hd TA2)
        (is-hd TA3)
        (is-hd BR1)
        (is-hd BR2)
        (is-hd BR3)
        (is-hd LE1)
        (is-hd LE2)
        (is-hd LE3)
        (is-hd CZ1)
        (is-hd CZ2)
        (is-hd CZ3)
        (is-hd KR1)
        (is-hd KR2)
        (is-hd KR3)
        (is-hd CS1)
        (is-hd CS2)
        (is-hd CS3)
        (is-hd VV1)
        (is-hd VV2)
        (is-hd VV3)
        (is-hd RC1)
        (is-hd RC2)
        (is-hd RC3)
        (is-hd RE11)
        (is-hd RE12)
        (is-hd RE13)
        (is-hd CT1)
        (is-hd CT2)
        (is-hd CT3)
        (is-hd ME1)
        (is-hd ME2)
        (is-hd ME3)
        (is-hd PA1)
        (is-hd PA2)
        (is-hd PA3)
        (is-hd AG1)
        (is-hd AG2)
        (is-hd AG3)
        (is-hd TP1)
        (is-hd TP2)
        (is-hd TP3)
        (is-hd EN1)
        (is-hd EN2)
        (is-hd EN3)
        (is-hd PU1)
        (is-hd PU2)
        (is-hd PU3)
        (is-hd AN1)
        (is-hd AN2)
        (is-hd AN3)
        (is-hd MC1)
        (is-hd MC2)
        (is-hd MC3)
        (is-hd AP1)
        (is-hd AP2)
        (is-hd AP3)
        (is-hd FM1)
        (is-hd FM2)
        (is-hd FM3)
        (is-hd MA11)
        (is-hd MA12)
        (is-hd MA13)
        (is-hd PG1)
        (is-hd PG2)
        (is-hd PG3)
        (is-hd TR1)
        (is-hd TR2)
        (is-hd TR3)
        (is-hd UM11)
        (is-hd UM12)
        (is-hd UM13)
        (is-hd UM21)
        (is-hd UM22)
        (is-hd UM23)
        (is-hd UM31)
        (is-hd UM32)
        (is-hd UM33)
        (is-hd UM41)
        (is-hd UM42)
        (is-hd UM43)
        (is-hd FI1)
        (is-hd FI2)
        (is-hd FI3)
        (is-hd PI1)
        (is-hd PI2)
        (is-hd PI3)
        (is-hd LI1)
        (is-hd LI2)
        (is-hd LI3)
        (is-hd GR1)
        (is-hd GR2)
        (is-hd GR3)
        (is-hd AR1)
        (is-hd AR2)
        (is-hd AR3)
        (is-hd SI1)
        (is-hd SI2)
        (is-hd SI3)
        (is-hd BO1)
        (is-hd BO2)
        (is-hd BO3)
        (is-hd FC1)
        (is-hd FC2)
        (is-hd FC3)
        (is-hd PR1)
        (is-hd PR2)
        (is-hd PR3)
        (is-hd RA1)
        (is-hd RA2)
        (is-hd RA2)
        (is-hd MO1)
        (is-hd MO2)
        (is-hd MO3)
        (is-hd FE1)
        (is-hd FE2)
        (is-hd FE3)
        (is-hd PC1)
        (is-hd PC2)
        (is-hd PC3)
        (is-hd VR1)
        (is-hd VR2)
        (is-hd VR3)
        (is-hd VE1)
        (is-hd VE2)
        (is-hd VE3)
        (is-hd VI1)
        (is-hd VI2)
        (is-hd VI3)
        (is-hd BL1)
        (is-hd BL2)
        (is-hd BL3)
        (is-hd PD1)
        (is-hd PD2)
        (is-hd PD3)
        (is-hd TV1)
        (is-hd TV2)
        (is-hd TV3)
        (is-hd MI1)
        (is-hd MI2)
        (is-hd MI3)
        (is-hd MN1)
        (is-hd MN2)
        (is-hd MN3)
        (is-hd BS1)
        (is-hd BS2)
        (is-hd BS3)
        (is-hd BG1)
        (is-hd BG2)
        (is-hd BG3)
        (is-hd LC1)
        (is-hd LC2)
        (is-hd LC3)
        (is-hd PV1)
        (is-hd PV2)
        (is-hd PV3)
        (is-hd TO1)
        (is-hd TO2)
        (is-hd TO3)
        (is-hd AL1)
        (is-hd AL2)
        (is-hd AL3)
        (is-hd AT1)
        (is-hd AT2)
        (is-hd AT3)
        (is-hd CN1)
        (is-hd CN2)
        (is-hd CN3)
        (is-hd VC1)
        (is-hd VC2)
        (is-hd VC3)
        (is-hd VB1)
        (is-hd VB2)
        (is-hd VB3)
        (is-hd GE1)
        (is-hd GE2)
        (is-hd GE3)
        (is-hd SP1)
        (is-hd SP2)
        (is-hd SP3)
        (is-hd IM1)
        (is-hd IM2)
        (is-hd IM3)
        (is-hd SV1)
        (is-hd SV2)
        (is-hd SV3)
        (is-hd LI11)
        (is-hd LI12)
        (is-hd LI13)
        (is-hd LI21)
        (is-hd LI22)
        (is-hd LI23)
        (is-hd TRE1)
        (is-hd TRE2)
        (is-hd TRE3)
        (is-hd BZ1)
        (is-hd BZ2)
        (is-hd BZ3)
        (is-hd AA11)
        (is-hd AA12)
        (is-hd AA13)
        (is-hd AA21)
        (is-hd AA22)
        (is-hd AA23)
        (is-hd AA31)
        (is-hd AA32)
        (is-hd AA33)
        (is-hd AA41)
        (is-hd AA42)
        (is-hd AA43)
        (is-hd AO11)
        (is-hd AO12)
        (is-hd AO13)
        (is-hd AO21)
        (is-hd AO22)
        (is-hd AO23)
        (is-hd AO31)
        (is-hd AO32)
        (is-hd AO33)
        (is-hd AO41)
        (is-hd AO42)
        (is-hd AO43)
        (is-hd AO51)
        (is-hd AO52)
        (is-hd AO53)
        (is-hd AO61)
        (is-hd AO62)
        (is-hd AO63)
        (is-hd PN1)
        (is-hd PN2)
        (is-hd PN3)
        (is-hd UD1)
        (is-hd UD2)
        (is-hd UD3)
        (is-hd TS1)
        (is-hd TS2)
        (is-hd TS3)
        (is-hd GO1)
        (is-hd GO2)
        (is-hd GO3)
        (is-hd FRI11)
        (is-hd FRI12)
        (is-hd FRI13)
        (is-hd FRI21)
        (is-hd FRI22)
        (is-hd FRI23)
        (is-hd CAG1)
        (is-hd CAG2)
        (is-hd CAG3)
        (is-hd NU1)
        (is-hd NU2)
        (is-hd NU3)
        (is-hd ORI1)
        (is-hd ORI2)
        (is-hd ORI3)
        (is-hd SS1)
        (is-hd SS2)
        (is-hd SS3)
        (is-hd SAR11)
        (is-hd SAR12)
        (is-hd SAR13)
        (is-hd SAR21)
        (is-hd SAR22)
        (is-hd SAR23)


	    
    ;INIT POSITIONS FOR THE OBJECTS
        ;TRUCKS
	    (at truck1 LAZIO) (at truck2 LAZIO) (at truck3 LAZIO) (at truck4 LAZIO) (at truck5 LAZIO) 
        (at truck6 LAZIO) (at truck7 LAZIO) (at truck8 LAZIO) (at truck9 LAZIO) (at truck10 LAZIO) 
        (at truck11 LAZIO) (at truck12 LAZIO) (at truck13 LAZIO) (at truck14 LAZIO) (at truck15 LAZIO) 
        (at truck16 ME) (at truck17 CT) (at truck18 NU) (at truck19 CA) (at truck20 EN) 
	    ;PLANES
	    (at plane1 RM) (at plane2 RM) (at plane3 RM) (at plane4 TO) (at plane5 NA)
        (at plane6 CA) (at plane7 PA) (at plane8 BO) (at plane9 CZ) (at plane10 RM)
        ;DRONES
        (at drone1 RM) (at drone2 VT) (at drone3 LZ1) (at drone4 RI) (at drone5 LT) (at drone6 FR) 
        (at drone7 CH) (at drone8 PE) (at drone9 TE) (at drone10 AQ) (at drone11 AB1) (at drone12 AB2) 
        (at drone13 IS) (at drone14 CB) (at drone15 MO1) (at drone16 MO2) (at drone17 MO3) (at drone18 MO4) 
        (at drone19 NA) (at drone20 CE) (at drone21 AV) (at drone22 BN) (at drone23 CA1) (at drone24 CA2) 
        (at drone25 MT) (at drone26 PZ) (at drone27 BA1) (at drone28 BA2) (at drone29 BA3) (at drone30 BA4)
        (at drone31 FG) (at drone32 BT) (at drone33 BA) (at drone34 TA) (at drone35 BR) (at drone36 LE) 
        (at drone37 CZ) (at drone38 KR) (at drone39 CS) (at drone40 VV) (at drone41 RC) (at drone42 RE1) 
        (at drone43 CT) (at drone44 ME) (at drone45 PA) (at drone46 AG) (at drone47 TP) (at drone48 EN) 
        (at drone49 PU) (at drone50 AN) (at drone51 MC) (at drone52 AP) (at drone53 FM) (at drone54 MA1) 
        (at drone55 PG) (at drone56 TR) (at drone57 UM1) (at drone58 UM2) (at drone59 UM3) (at drone60 UM4) 
        (at drone61 FI) (at drone62 PI) (at drone63 LI) (at drone64 GR) (at drone65 AR) (at drone66 SI) 
        (at drone67 BO) (at drone68 FC) (at drone69 PR) (at drone70 RA) (at drone71 MO) (at drone72 FE) (at drone73 PC)
        (at drone74 VR) (at drone75 VE) (at drone76 VI) (at drone77 BL) (at drone78 PD) (at drone79 TV) 
        (at drone80 MI) (at drone81 MN) (at drone82 BS) (at drone83 BG) (at drone84 LC) (at drone85 PV) 
        (at drone86 TO) (at drone87 AL) (at drone88 AT) (at drone89 CN) (at drone90 VC) (at drone91 VB) 
        (at drone92 GE) (at drone93 SP) (at drone94 IM) (at drone95 SV) (at drone96 LI1) (at drone97 LI2) 
        (at drone98 TRE) (at drone99 BZ) (at drone100 AA1) (at drone101 AA2) (at drone102 AA3) (at drone103 AA4) 
        (at drone104 AO1) (at drone105 AO2) (at drone106 AO3) (at drone107 AO4) (at drone108 AO5) (at drone109  AO6) 
        (at drone110 PN) (at drone111 UD) (at drone112 TS) (at drone113 GO) (at drone114 FRI1) (at drone115 FRI2) 
        (at drone116 CAG) (at drone117 NU) (at drone118 ORI) (at drone119 SS) (at drone120 SAR1) (at drone121 SAR2) 
	
		
	)
	
	(:goal 	
		(and    ( = (capacity RM1) 1)
                ( = (capacity RM2) 1)
                ( = (capacity RM3) 1)
                ( = (capacity VT1) 1)
                ( = (capacity VT2) 1)
                ( = (capacity VT3) 1)
                ( = (capacity LZ11) 1)
                ( = (capacity LZ12) 1)
                ( = (capacity LZ13) 1)
                ( = (capacity RI1) 1)
                ( = (capacity RI2) 1)
                ( = (capacity RI3) 1)
                ( = (capacity LT1) 1)
                ( = (capacity LT2) 1)
                ( = (capacity LT3) 1)
                ( = (capacity FR1) 1)
                ( = (capacity FR2) 1)
                ( = (capacity FR3) 1)
                ( = (capacity CH1) 1)
                ( = (capacity CH2) 1)
                ( = (capacity CH3) 1)
                ( = (capacity PE1) 1)
                ( = (capacity PE2) 1)
                ( = (capacity PE3) 1)
                ( = (capacity TE1) 1)
                ( = (capacity TE2) 1)
                ( = (capacity TE3) 1)
                ( = (capacity AQ1) 1)
                ( = (capacity AQ2) 1)
                ( = (capacity AQ3) 1)
                ( = (capacity AB11) 1)
                ( = (capacity AB12) 1)
                ( = (capacity AB13) 1)
                ( = (capacity AB21) 1)
                ( = (capacity AB22) 1)
                ( = (capacity AB23) 1)
                ( = (capacity IS1) 1)
                ( = (capacity IS2) 1)
                ( = (capacity IS3) 1)
                ( = (capacity CB1) 1)
                ( = (capacity CB2) 1)
                ( = (capacity CB3) 1)
                ( = (capacity MO11) 1)
                ( = (capacity MO12) 1)
                ( = (capacity MO13) 1)
                ( = (capacity MO21) 1)
                ( = (capacity MO22) 1)
                ( = (capacity MO23) 1)
                ( = (capacity MO31) 1)
                ( = (capacity MO32) 1)
                ( = (capacity MO33) 1)
                ( = (capacity MO41) 1)
                ( = (capacity MO42) 1)
                ( = (capacity MO43) 1)
                ( = (capacity NA1) 1)
                ( = (capacity NA2) 1)
                ( = (capacity NA3) 1)
                ( = (capacity CE1) 1)
                ( = (capacity CE2) 1)
                ( = (capacity CE3) 1)
                ( = (capacity AV1) 1)
                ( = (capacity AV2) 1)
                ( = (capacity AV3) 1)
                ( = (capacity BN1) 1)
                ( = (capacity BN2) 1)
                ( = (capacity BN3) 1)
                ( = (capacity CA11) 1)
                ( = (capacity CA12) 1)
                ( = (capacity CA13) 1)
                ( = (capacity CA21) 1)
                ( = (capacity CA22) 1)
                ( = (capacity CA23) 1)
                ( = (capacity MT1) 1)
                ( = (capacity MT2) 1)
                ( = (capacity MT3) 1)
                ( = (capacity PZ1) 1)
                ( = (capacity PZ2) 1)
                ( = (capacity PZ3) 1)
                ( = (capacity BA11) 1)
                ( = (capacity BA12) 1)
                ( = (capacity BA13) 1)
                ( = (capacity BA21) 1)
                ( = (capacity BA22) 1)
                ( = (capacity BA23) 1)
                ( = (capacity BA31) 1)
                ( = (capacity BA32) 1)
                ( = (capacity BA33) 1)
                ( = (capacity BA41) 1)
                ( = (capacity BA42) 1)
                ( = (capacity BA43) 1)
                ( = (capacity FG1) 1)
                ( = (capacity FG2) 1)
                ( = (capacity FG3) 1)
                ( = (capacity BT1) 1)
                ( = (capacity BT2) 1)
                ( = (capacity BT3) 1)
                ( = (capacity BA1) 1)
                ( = (capacity BA2) 1)
                ( = (capacity BA3) 1)
                ( = (capacity TA1) 1)
                ( = (capacity TA2) 1)
                ( = (capacity TA3) 1)
                ( = (capacity BR1) 1)
                ( = (capacity BR2) 1)
                ( = (capacity BR3) 1)
                ( = (capacity LE1) 1)
                ( = (capacity LE2) 1)
                ( = (capacity LE3) 1)
                ( = (capacity CZ1) 1)
                ( = (capacity CZ2) 1)
                ( = (capacity CZ3) 1)
                ( = (capacity KR1) 1)
                ( = (capacity KR2) 1)
                ( = (capacity KR3) 1)
                ( = (capacity CS1) 1)
                ( = (capacity CS2) 1)
                ( = (capacity CS3) 1)
                ( = (capacity VV1) 1)
                ( = (capacity VV2) 1)
                ( = (capacity VV3) 1)
                ( = (capacity RC1) 1)
                ( = (capacity RC2) 1)
                ( = (capacity RC3) 1)
                ( = (capacity RE11) 1)
                ( = (capacity RE12) 1)
                ( = (capacity RE13) 1)
                ( = (capacity CT1) 1)
                ( = (capacity CT2) 1)
                ( = (capacity CT3) 1)
                ( = (capacity ME1) 1)
                ( = (capacity ME2) 1)
                ( = (capacity ME3) 1)
                ( = (capacity PA1) 1)
                ( = (capacity PA2) 1)
                ( = (capacity PA3) 1)
                ( = (capacity AG1) 1)
                ( = (capacity AG2) 1)
                ( = (capacity AG3) 1)
                ( = (capacity TP1) 1)
                ( = (capacity TP2) 1)
                ( = (capacity TP3) 1)
                ( = (capacity EN1) 1)
                ( = (capacity EN2) 1)
                ( = (capacity EN3) 1)
                ( = (capacity PU1) 1)
                ( = (capacity PU2) 1)
                ( = (capacity PU3) 1)
                ( = (capacity AN1) 1)
                ( = (capacity AN2) 1)
                ( = (capacity AN3) 1)
                ( = (capacity MC1) 1)
                ( = (capacity MC2) 1)
                ( = (capacity MC3) 1)
                ( = (capacity AP1) 1)
                ( = (capacity AP2) 1)
                ( = (capacity AP3) 1)
                ( = (capacity FM1) 1)
                ( = (capacity FM2) 1)
                ( = (capacity FM3) 1)
                ( = (capacity MA11) 1)
                ( = (capacity MA12) 1)
                ( = (capacity MA13) 1)
                ( = (capacity PG1) 1)
                ( = (capacity PG2) 1)
                ( = (capacity PG3) 1)
                ( = (capacity TR1) 1)
                ( = (capacity TR2) 1)
                ( = (capacity TR3) 1)
                ( = (capacity UM11) 1)
                ( = (capacity UM12) 1)
                ( = (capacity UM13) 1)
                ( = (capacity UM21) 1)
                ( = (capacity UM22) 1)
                ( = (capacity UM23) 1)
                ( = (capacity UM31) 1)
                ( = (capacity UM32) 1)
                ( = (capacity UM33) 1)
                ( = (capacity UM41) 1)
                ( = (capacity UM42) 1)
                ( = (capacity UM43) 1)
                ( = (capacity FI1) 1)
                ( = (capacity FI2) 1)
                ( = (capacity FI3) 1)
                ( = (capacity PI1) 1)
                ( = (capacity PI2) 1)
                ( = (capacity PI3) 1)
                ( = (capacity LI1) 1)
                ( = (capacity LI2) 1)
                ( = (capacity LI3) 1)
                ( = (capacity GR1) 1)
                ( = (capacity GR2) 1)
                ( = (capacity GR3) 1)
                ( = (capacity AR1) 1)
                ( = (capacity AR2) 1)
                ( = (capacity AR3) 1)
                ( = (capacity SI1) 1)
                ( = (capacity SI2) 1)
                ( = (capacity SI3) 1)
                ( = (capacity BO1) 1)
                ( = (capacity BO2) 1)
                ( = (capacity BO3) 1)
                ( = (capacity FC1) 1)
                ( = (capacity FC2) 1)
                ( = (capacity FC3) 1)
                ( = (capacity PR1) 1)
                ( = (capacity PR2) 1)
                ( = (capacity PR3) 1)
                ( = (capacity RA1) 1)
                ( = (capacity RA2) 1)
                ( = (capacity RA3) 1)
                ( = (capacity MO1) 1)
                ( = (capacity MO2) 1)
                ( = (capacity MO3) 1)
                ( = (capacity FE1) 1)
                ( = (capacity FE2) 1)
                ( = (capacity FE3) 1)
                ( = (capacity PC1) 1)
                ( = (capacity PC2) 1)
                ( = (capacity PC3) 1)
                ( = (capacity VR1) 1)
                ( = (capacity VR2) 1)
                ( = (capacity VR3) 1)
                ( = (capacity VE1) 1)
                ( = (capacity VE2) 1)
                ( = (capacity VE3) 1)
                ( = (capacity VI1) 1)
                ( = (capacity VI2) 1)
                ( = (capacity VI3) 1)
                ( = (capacity BL1) 1)
                ( = (capacity BL2) 1)
                ( = (capacity BL3) 1)
                ( = (capacity PD1) 1)
                ( = (capacity PD2) 1)
                ( = (capacity PD3) 1)
                ( = (capacity TV1) 1)
                ( = (capacity TV2) 1)
                ( = (capacity TV3) 1)
                ( = (capacity MI1) 1)
                ( = (capacity MI2) 1)
                ( = (capacity MI3) 1)
                ( = (capacity MN1) 1)
                ( = (capacity MN2) 1)
                ( = (capacity MN3) 1)
                ( = (capacity BS1) 1)
                ( = (capacity BS2) 1)
                ( = (capacity BS3) 1)
                ( = (capacity BG1) 1)
                ( = (capacity BG2) 1)
                ( = (capacity BG3) 1)
                ( = (capacity LC1) 1)
                ( = (capacity LC2) 1)
                ( = (capacity LC3) 1)
                ( = (capacity PV1) 1)
                ( = (capacity PV2) 1)
                ( = (capacity PV3) 1)
                ( = (capacity TO1) 1)
                ( = (capacity TO2) 1)
                ( = (capacity TO3) 1)
                ( = (capacity AL1) 1)
                ( = (capacity AL2) 1)
                ( = (capacity AL3) 1)
                ( = (capacity AT1) 1)
                ( = (capacity AT2) 1)
                ( = (capacity AT3) 1)
                ( = (capacity CN1) 1)
                ( = (capacity CN2) 1)
                ( = (capacity CN3) 1)
                ( = (capacity VC1) 1)
                ( = (capacity VC2) 1)
                ( = (capacity VC3) 1)
                ( = (capacity VB1) 1)
                ( = (capacity VB2) 1)
                ( = (capacity VB3) 1)
                ( = (capacity GE1) 1)
                ( = (capacity GE2) 1)
                ( = (capacity GE3) 1)
                ( = (capacity SP1) 1)
                ( = (capacity SP2) 1)
                ( = (capacity SP3) 1)
                ( = (capacity IM1) 1)
                ( = (capacity IM2) 1)
                ( = (capacity IM3) 1)
                ( = (capacity SV1) 1)
                ( = (capacity SV2) 1)
                ( = (capacity SV3) 1)
                ( = (capacity LI11) 1)
                ( = (capacity LI12) 1)
                ( = (capacity LI13) 1)
                ( = (capacity LI21) 1)
                ( = (capacity LI22) 1)
                ( = (capacity LI23) 1)
                ( = (capacity TRE1) 1)
                ( = (capacity TRE2) 1)
                ( = (capacity TRE3) 1)
                ( = (capacity BZ1) 1)
                ( = (capacity BZ2) 1)
                ( = (capacity BZ3) 1)
                ( = (capacity AA11) 1)
                ( = (capacity AA12) 1)
                ( = (capacity AA13) 1)
                ( = (capacity AA21) 1)
                ( = (capacity AA22) 1)
                ( = (capacity AA23) 1)
                ( = (capacity AA31) 1)
                ( = (capacity AA32) 1)
                ( = (capacity AA33) 1)
                ( = (capacity AA41) 1)
                ( = (capacity AA42) 1)
                ( = (capacity AA43) 1)
                ( = (capacity AO11) 1)
                ( = (capacity AO12) 1)
                ( = (capacity AO13) 1)
                ( = (capacity AO21) 1)
                ( = (capacity AO22) 1)
                ( = (capacity AO23) 1)
                ( = (capacity AO31) 1)
                ( = (capacity AO32) 1)
                ( = (capacity AO33) 1)
                ( = (capacity AO41) 1)
                ( = (capacity AO42) 1)
                ( = (capacity AO43) 1)
                ( = (capacity AO51) 1)
                ( = (capacity AO52) 1)
                ( = (capacity AO53) 1)
                ( = (capacity AO61) 1)
                ( = (capacity AO62) 1)
                ( = (capacity AO63) 1)
                ( = (capacity PN1) 1)
                ( = (capacity PN2) 1)
                ( = (capacity PN3) 1)
                ( = (capacity UD1) 1)
                ( = (capacity UD2) 1)
                ( = (capacity UD3) 1)
                ( = (capacity TS1) 1)
                ( = (capacity TS2) 1)
                ( = (capacity TS3) 1)
                ( = (capacity GO1) 1)
                ( = (capacity GO2) 1)
                ( = (capacity GO3) 1)
                ( = (capacity FRI11) 1)
                ( = (capacity FRI12) 1)
                ( = (capacity FRI13) 1)
                ( = (capacity FRI21) 1)
                ( = (capacity FRI22) 1)
                ( = (capacity FRI23) 1)
                ( = (capacity CAG1) 1)
                ( = (capacity CAG2) 1)
                ( = (capacity CAG3) 1)
                ( = (capacity NU1) 1)
                ( = (capacity NU2) 1)
                ( = (capacity NU3) 1)
                ( = (capacity ORI1) 1)
                ( = (capacity ORI2) 1)
                ( = (capacity ORI3) 1)
                ( = (capacity SS1) 1)
                ( = (capacity SS2) 1)
                ( = (capacity SS3) 1)
                ( = (capacity SAR11) 1)
                ( = (capacity SAR12) 1)
                ( = (capacity SAR13) 1)
                ( = (capacity SAR21) 1)
                ( = (capacity SAR22) 1)
                ( = (capacity SAR23) 1)
		)
	)
)
